### ISSUE TITLE
Gnome 3.24 compatibility improvement

### ISSUE THREAD

**Issue by franglais125** [franglais125/no-title-bar#1]
@jhasse I reworked your fix and included it in my master [03cfa652acf1fec617db8a36524a81c1ba1d9f9b]. I essentially added a version compatibility function to check if the unmax/max function needs to be triggered.

Does this work for you on 3.24? This way we are compatible with Shell versions below or above 3.24.

**Comment by franglais125** [comment]
I also pushed two more of your fixes:
- [3a866ce822995245eb36c5dfa98b9b09bb551ea2]: fix undeclared warnings
- [d830c0a258af4e94dd9a766bac6e9635df1a700f]: modal dialogs

Thanks a lot for the heads up! If you don't mind testing, it would be great to know that this fork is compatible with your Gnome 3.24 setup.

I do intend to maintain this.

**Comment by jhasse** [comment]
Awesome stuff! That version check is a good idea.

I've just tried it on 3.24 and it worked (no restore/maximize of all maximized windows taking place when unlocking the screen).

**Comment by franglais125** [comment]
Great to hear! I'll close this issue now, but feel free to open new ones of course :)

Cheers!
