### ISSUE TITLE
Not working on second monitor on Ubuntu 18.04

### ISSUE THREAD

**Issue by leynebe** [franglais125/no-title-bar#100]
Doesn't seem to be working when using a second monitor on Ubuntu 18.04. This is a fresh install.

[pic1-without-status-bar-extension](https://imgur.com/a/zuAvOOu)

The status bar is also not visible on the second monitor. I enabled it with a second plugin but to no avail.

[pic2-with-status-bar-extension](https://imgur.com/a/1R4VdrY)

Thanks in advance

**Comment by gombosg** [comment]
Same here on Fedora 29. Title bar is not hidden on external screen, but works fine on the primary screen.

**Comment by Ramesh-X** [comment]
is there a fix for this yet?
Same problem. Ubuntu 18.04
