### ISSUE TITLE
Multi-monitor support (placeholder)

### ISSUE THREAD

**Issue by franglais125** [franglais125/no-title-bar#14]
This is just an announcement to some people I found asking about this. I implemented a feature to deactivate "pixel-saver" on secondary monitors. I uploaded the fork here: https://extensions.gnome.org/extension/1267/no-title-bar/

@the0demiurge @NNois @Zbob750 @1029chris @arcresu @passcod @highvoltage @hackel @kmhofmann @shihrer @overjt @nxadm @cfviotti

**Comment by passcod** [comment]
Any reason why this isn't a Pull Request on the original?

**Comment by kmhofmann** [comment]
The original author was reluctant to merge in anything related to that feature, or didn't react anymore at all? See the discussion here: https://github.com/deadalnix/pixel-saver/pull/115

**Comment by franglais125** [comment]
Exactly. I merged a couple of other PRs as well into this fork.

**Comment by franglais125** [comment]
Tagging @guenhter

**Comment by guenhter** [comment]
@franglais125 do you plan to create a pull-request for your changes or do you develop this fork independently?

**Comment by franglais125** [comment]
I created a PR for this feature months ago (see link above), but the reluctance of the maintainer to include any settings at all made me close that PR and simply fork it for good.

If you go to the PR, you can see I indeed tried to collaborate, as I hate having duplication of effort, and I maintain other extensions as well. But in the end, it was hurting users not having any settings at all.

**Comment by guenhter** [comment]
Ah, I see. You really put a lot of effort into this. Very sad do hear that your hard work isn't appreciated by the author...

**Comment by shihrer** [comment]
👍 

Thanks for implementing this (and for bringing it to my attention).  I'll have to check it out sometime.

**Comment by franglais125** [comment]
@guenhter Well, I don't want to say that the original author didn't appreciate it, he might be very busy! If anything the lack of feedback was the frustrating part...

Anyway, I'm glad people find it helpful.

**Comment by franglais125** [comment]
@NNois Give this extension a try, I've included the multi-monitor support.

**Comment by NNois** [comment]
@franglais125 just perfect ! congrats
