### ISSUE TITLE
Wayland, GTK4 and plans for the future

### ISSUE THREAD

**Issue by mmoya** [franglais125/no-title-bar#19]
The README says it's impossible to work under Wayland because:

> The necessary support is simply not available upstream, and can't be fixed at the extension level

it's possible to document better what is missing for Wayland in order to ease tracking with upstream or look for alternatives?

**Comment by franglais125** [comment]
Thanks for taking the time of opening this issue! I apologize for my late reply. This was opened when I was traveling and then I totally forgot to answer.

Documenting what is missing would actually not help, as GNOME is in fact moving in the *opposite* direction:
- In order for this extension to work, we make use of a command (`xprop`) that sets a window property (`GTK_HIDE_TITLEBAR_WHEN_MAXIMIZED`). It's up to the compositor then to honor this property and remove the title bar.
- This property was only implemented for the X backend, meaning that similar work would be needed (upstream) in order for this to work in Wayland.
- However, for GTK 4, this was *removed* altogether, for X and for Wayland.

This means that this extension is tied to whatever we have in GTK 3. But this is not all negative - many applications (within GNOME at least) are moving to CSD style windows, meaning that there is no title bar to be removed (for instance Nautilus).

--------------------------------------------------------------------------
Sorry I don't have better news, but this is the current status. Summarizing:
1. It only works for X for now - unless you patch GTK 3 yourself and rebuild it.
2. No support will be added for Wayland, support for X will was *removed* (GTK4).
3. Applications are moving to CSD anyway.

For more information:
- Related bug: https://bugzilla.gnome.org/show_bug.cgi?id=775061
- Commit removing support in GTK 4: https://git.gnome.org/browse/gtk%2B/commit/?id=92b0d2e
- Relevant Pixel Saver bug: https://github.com/deadalnix/pixel-saver/issues/32

--------------------------------------------------------------------------
I'll keep this issue open as a placeholder. Again, thank you for your attention!

**Comment by franglais125** [comment]
Using CSS, I was able to hide the title bars. This is not the ideal solution but it works quite well honestly (took the idea from the "unite" extension).

I'll close this now!
