### ISSUE TITLE
GNOME 3.26 session crash

### ISSUE THREAD

**Issue by michaudg** [franglais125/no-title-bar#30]
When no-title-bar extension is active, session is crashing when closing a maximized window from the activities overview.

**Comment by franglais125** [comment]
Thanks a lot for reporting this!

1. Is this on Wayland or Xorg? And does it happen with any application you close?
2. Could you attach errors from the log, if any? Here is how to get them:
```
sudo journalctl /usr/bin/gnome-shell
```

**Comment by michaudg** [comment]
Sorry, it was a mistake. My session crashes even without any active extensions. Maybe it's a GNOME 3.26.1 bug.

Thanks for your work on this extension.
