### ISSUE TITLE
Make install fails on debian 9

### ISSUE THREAD

**Issue by guenhter** [franglais125/no-title-bar#31]
Hi, 

I get the following error when executing `make install`:

```
make install

msgfmt -c po/es.po -o po/es.mo
make: msgfmt: Command not found
Makefile:50: recipe for target 'po/es.mo' failed
make: *** [po/es.mo] Error 127
```

OS:
`Linux everest_grg 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux`

Dependencies seems also be available:

```
sudo apt install x11-utils

Reading package lists... Done
Building dependency tree       
Reading state information... Done
x11-utils is already the newest version (7.7+3+b1).
x11-utils set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

What am I missing?

**Comment by franglais125** [comment]
Thanks for opening the issue. I think you are missing the formatting libraries (for internationalization).

Can you try with: `sudo apt install gettext` ?

**Comment by guenhter** [comment]
Thanks. That was the problem.
Great tool btw. Totally worth it to give it a try.
