### ISSUE TITLE
Doesn't affect gnome-terminal

### ISSUE THREAD

**Issue by integrics** [franglais125/no-title-bar#34]
Have installed this extension, and it works for Firefox and Thunderbird, but doesn't seem to affect gnome-terminal 3.24.2 running on Ubuntu 17.10.

**Comment by franglais125** [comment]
Hi! Thanks for reporting this. You are most likely using the Wayland session... Unfortunately, we can't remove the titlebars on Wayland. The reason Firefox and Thunderbird work is because they are not native Wayland clients, and work through XWayland.

If you feel like installing the latest code from git, I've added a css class that takes care of this problem for some apps in Wayland, but there is only so much we can do.

Can you confirm this? Are you on Wayland?

**Comment by integrics** [comment]
Yes, I've just upgraded to Ubuntu 17.10 which uses Wayland.

**Comment by franglais125** [comment]
If you feel like it, you can test the code directly from git, which has a few more commits not yet released to extensions.gnome.org.

Some feedback on that would be great.

**Comment by integrics** [comment]
Would you have any instructions on how to do that for someone who only started using Gnome extensions a few hours ago?

**Comment by franglais125** [comment]
Sure, here it is:

```
git clone https://github.com/franglais125/no-title-bar
cd no-title-bar
make install
```

Log out and log in again. You might need to install a few things:
```
sudo apt install make git gettext
```

**Comment by integrics** [comment]
Thank you, that works. Do you have any plans to include this feature in the official release?

**Comment by franglais125** [comment]
Yes! The problem I have now is that I can't selectively apply the css classes, it's either all or nothing, so some options in the GUI are useless.

I want to see how to deal with this first.

**Comment by szuliq** [comment]
Now the Ubuntu 17.10 is out (Wayland + drop Unity) I believe this is a great time for "No Title Bar" to gain popularity. People want all the space they can get, especially on small screens.

Did you consider making a note regarding Wayland on the extension's page?

Great work, thanks for the extension.

**Comment by franglais125** [comment]
@szuliq Thanks for the feedback! I now added a note concerning Wayland support.

A new version as uploaded and is awaiting review. I'll close this issue now.

Thanks everyone!
