### ISSUE TITLE
wayland version: menu bar clicks "redirected" to wrong button

### ISSUE THREAD

**Issue by zaphot** [franglais125/no-title-bar#36]
Hi,
im using your current master version under ubuntu 17.10 wayland (gnome-session) and have the 
problem that clicks on the menu bar in fullscreen wayland applications are sometimes redirected to the first button on the left. In the attached screenshot you can see that i click on "insert" and the "file" menu opens.
This only happens with no-title-bar installed. But could be a more general gtk issue?

![screenshot from 2017-10-24 12-39-01](https://user-images.githubusercontent.com/29272806/31938766-bf904984-b8b8-11e7-9517-76eb60655110.png)

**Comment by franglais125** [comment]
Thanks a lot for reporting this issue!

Unfortunately, I can't reproduce the problem on Debian Testing with LibreOffice `5.4.2`.

- Does this occur all the time?
- What version of LO are you running?

The bad news is that I doubt I can fix this on my end, as you say it looks like it's a deeper problem within GTK and some wayland layer in LO. As far as I know, LibreOffice is improving its Wayland support in the last few versions. Chances are this problem will go away in Ubuntu 18.04.

**Comment by zaphot** [comment]
thanks for replying!
- this issue occurs always
- It is not limited to libreoffice (i am using version 5.4.1.2) but affects every wayland fullscreen application like for example shotwell (see screenshot).
![screenshot from 2017-10-29 15-16-18](https://user-images.githubusercontent.com/29272806/32144711-71d877b2-bcbd-11e7-96a9-6b4cfee01860.png)

**Comment by franglais125** [comment]
Hmm, I can't reproduce this with Shotwell either (in Wayland obviously).

Are there any (relevant) errors in the logs? Can you check this?

`sudo journalctl /usr/bin/gnome-shell`

or `sudo journalctl /usr/bin/gnome-shell -f` to see new errors as they happen.

**Comment by zaphot** [comment]
don't think any relevant is in the log, since nothing is added if i perform "wrong clicks". Only one small thing that concerns your extensions:

> Okt 29 18:14:23 t440s gnome-shell[1353]: JS ERROR: TypeError: title is null
>                                          Decoration<._guessWindowXID@/home/thorsten/.local/share/gnome-shell/extensions/no-title-bar@franglais125.gmail.com/decoration.js:249:21
>                                          wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>                                          Decoration<._setHideTitlebar@/home/thorsten/.local/share/gnome-shell/extensions/no-title-bar@franglais125.gmail.com/decoration.js:384:22
>                                          wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>                                          Decoration<._windowEnteredMonitor@/home/thorsten/.local/share/gnome-shell/extensions/no-title-bar@franglais125.gmail.com/decoration.js:571:9

Debian testing is using gnome-shell 3.22 or? Ubuntu is already on 3.26, so maybe an gnome 3.26 issue.


However, here is the full log after a fresh boot into wayland session

> -- Logs begin at Sun 2017-10-29 18:14:05 CET. --
Okt 29 18:14:18 t440s gnome-shell[1353]: JS WARNING: [resource:///org/gnome/shell/ui/main.js 315]: reference to undefined property "MetaStage"
Okt 29 18:14:18 t440s gnome-shell[1353]: JS WARNING: [resource:///org/gnome/shell/ui/layout.js 221]: reference to undefined property "MetaWindowGroup"
Okt 29 18:14:18 t440s gnome-shell[1353]: JS WARNING: [resource:///org/gnome/shell/ui/osdMonitorLabeler.js 59]: reference to undefined property "MetaDBusDisplayConfigSkeleton"
Okt 29 18:14:18 t440s gnome-shell[1353]: JS WARNING: [resource:///org/gnome/shell/ui/slider.js 38]: reference to undefined property "CallyActor"
Okt 29 18:14:18 t440s gnome-shell[1353]: Telepathy is not available, chat integration will be disabled.
Okt 29 18:14:18 t440s gnome-shell[1353]: JS WARNING: [resource:///org/gnome/gjs/modules/tweener/tweener.js 540]: reference to undefined property "isSpecialProperty"
Okt 29 18:14:19 t440s gnome-shell[1353]: Error looking up permission: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.impl.portal.PermissionStore was not provided by any .service files
Okt 29 18:14:19 t440s org.gnome.Shell.desktop[1353]: Window manager warning: "XF86RFKill" is not a valid accelerator
Okt 29 18:14:20 t440s gnome-shell[1353]: GNOME Shell started at Sun Oct 29 2017 18:14:18 GMT+0100 (CET)
Okt 29 18:14:23 t440s gnome-shell[1353]: JS ERROR: TypeError: title is null
                                         Decoration<._guessWindowXID@/home/thorsten/.local/share/gnome-shell/extensions/no-title-bar@franglais125.gmail.com/decoration.js:249:21
                                         wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                         Decoration<._setHideTitlebar@/home/thorsten/.local/share/gnome-shell/extensions/no-title-bar@franglais125.gmail.com/decoration.js:384:22
                                         wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
                                         Decoration<._windowEnteredMonitor@/home/thorsten/.local/share/gnome-shell/extensions/no-title-bar@franglais125.gmail.com/decoration.js:571:9
                                         wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
Okt 29 18:17:49 t440s org.gnome.Shell.desktop[1353]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2200041 (Open Datab)
Okt 29 18:17:51 t440s org.gnome.Shell.desktop[1353]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2200041 (Open Datab)
Okt 29 18:17:51 t440s org.gnome.Shell.desktop[1353]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2200017 (browser_ke)

**Comment by franglais125** [comment]
Just to be safe, can you try again with master? I just added a commit to remove the debug variables, it should remove the error you were seeing...

By the way, just to be safe, do you have `xprop` installed?

--------------------------
> Debian testing is using gnome-shell 3.22 or? Ubuntu is already on 3.26, so maybe an gnome 3.26 issue.

Yes, Debian testing is on 3.22, but I installed 3.26 from unstable manually :)

**Comment by zaphot** [comment]
Hi, thanks but the click redirect still happens. However, the messages in the log are gone. Xprop is installed. So lets hope this just some wired ubuntu specific issue

**Comment by zaphot** [comment]
not happening anymore in ubuntu 18.04
