### ISSUE TITLE
After screen lock, window name in top bar stop follow title changes for active application

### ISSUE THREAD

**Issue by eugene-rom** [franglais125/no-title-bar#37]
Steps to reproduce:
1. Open application with multiple tabs with different names (Firefox/Chrome)
2. Press Super-L to lock screen
3. Unlock screen
4. Press Ctrl-PgUp/Ctrl-PgDn to change application tabs. Window name in top bar not follow tab changes.

Switching to another app and returning will restore correct behaviour. 

I think, as screen lock disables extensions, on calling "enable" method, no-title-bar not restore tracking for focused window title.

**Comment by franglais125** [comment]
Thanks a lot for reporting this. It was a known issue, I just didn't know how to reproduce it.

I fixed it here [8a1406af89ab61fcf21eb1e58dfae5f365f085d1]. Would you mind testing the latest master branch?

**Comment by eugene-rom** [comment]
Tested, looks like it fixed now! Thank you!

**Comment by franglais125** [comment]
Awesome! I won't be uploading a new version soon to e.g.o due to some experimental work I'm doing on Wayland, but I'll definitely include as soon as possible...

You can run the code from git for the time being :). Thanks for the feedback!
