### ISSUE TITLE
Properly restore the extension

### ISSUE THREAD

**Issue by franglais125** [franglais125/no-title-bar#4]
@Beanow

Hi! You commented on the pixel-saver PR, and mentioned that enabling/disabling the extension doesn't properly restore the state of windows.

I included a fix in this fork that tries to remedy this [b2c498048f84a88d2a1b75d3996f4f8cd8028d8a].

If you want to give it a try, please let me know if it works for you!

```
git clone https://github.com/franglais125/no-title-bar
cd no-title-bar
make install
gnome-shell-extension-tool -e no-title-bar@franglais125.gmail.com
```

Hopefully we'll see this fork available from e.g.o :)

Thank you!

**Comment by Beanow** [comment]
Sorry for taking a bit. That indeed fixes the issue for me. :+1:

**Comment by franglais125** [comment]
Thank you! I'll close the issue now. i'll try to remember to post here again when the extension is available from e.g.o so you know :)

**Comment by Beanow** [comment]
Looks like it already landed on ego.

**Comment by franglais125** [comment]
Indeed! Cheers
