### ISSUE TITLE
Error when install No Title Bar

### ISSUE THREAD

**Issue by ErickTucto** [franglais125/no-title-bar#43]
When I updated the plugin, He showed me the next error

![imagen](https://user-images.githubusercontent.com/22831024/33078371-76e2ec8e-cea0-11e7-88f8-6d3b176448db.png)

I also installed via git, but still showing the same error

**Comment by forteller** [comment]
Same here. Love this extension, hope you can find the fix :)

**Comment by anupam207** [comment]
Same as: https://github.com/franglais125/no-title-bar/issues/41 ?

**Comment by franglais125** [comment]
Hello all, thanks a lot for the prompt reporting of this problem! It was not obvious to trigger (in my usage at least).

Thanks a lot @nhinds for looking into this (#41), as I actually didn't have that much time to investigate.

I uploaded a new version to e.g.o with the fix. If anyone could confirm that the latest git code works it would be great.

I have to say I'm flattered by the great response to this issue.

Cheers everyone,
Fran

**Comment by franglais125** [comment]
I believe this was fixed in the latest upload. Closing this!
