### ISSUE TITLE
Specify title size

### ISSUE THREAD

**Issue by Spinnekop** [franglais125/no-title-bar#44]
Hi Franglais

Would it be possible to limit the size of the window name. I have dash to panel installed which moved the title to the right but sometimes the title is too long and there is overlap. FYI the budgie-pixel-saver does this if that helps at all. https://github.com/ilgarmehmetali/budgie-pixel-saver-applet.

**Comment by franglais125** [comment]
Yeah, this would be awesome to have. I want it for myself, I just need to find some time and do it! Patches welcome.

Thanks for opening this issue!

**Comment by Spinnekop** [comment]
I haven't done any coding for more than 20 years! My Cobol won't help!!

**Comment by franglais125** [comment]
Ask, and you shall receive: [d5e91ace411cf58e37d863e94fafa80e78620a30]

Would you mind testing the code from git?

General comment: when mentioning patches welcome, I don't mean that I expect them, but I indeed welcome them if they come :)

**Comment by Spinnekop** [comment]
Sorry dude - I have no title at all now - only the buttons....

**Comment by Spinnekop** [comment]
Idiot me - show appmenu was turned off (but I don't recall doing that!)

**Comment by Spinnekop** [comment]
Super super super!!!!

**Comment by franglais125** [comment]
Awesome! I'll close this... I'll publish a new version eventually including this feature. Cheers!
