### ISSUE TITLE
Feature Request: Treat GTiled Windows like Snapped Windows

### ISSUE THREAD

**Issue by jcuenod** [franglais125/no-title-bar#61]
I'm using gTile to move windows to certain parts of the screen (it's basically advanced snapping).
I don't need (or want) their title bars when they are in particular locations. I'm not sure how much data you can have exposed by gTile but, broadly speaking, I would like no-title-bar to respond to gTile like it can to snapping of windows.

**Comment by skewty** [comment]
if I am not mistaken, gTiled windows are just resized windows.  gTiled windows AFAIK cannot be detected as "Tiled".  I think you might be better off putting this feature request on gTiled itself.

It could keep a cache of which windows it tiled and when they get moved out of tile location, restore their controls.  That would be way out of scope for this project.

**Comment by jcuenod** [comment]
Ahh, that makes sense...

**Comment by jcuenod** [comment]
Good point, this makes sense. Thanks.
