### ISSUE TITLE
Monitor power-off causes title bar to reappear (or disappear)

### ISSUE THREAD

**Issue by uusijani** [franglais125/no-title-bar#77]
## Background
I'm using the currently published version of No Title Bar from Gnome Extensions in Ubuntu 18.04 (gnome-shell version 3.28.1-0ubuntu2).

## Steps to reproduce

1. log in to desktop
2. start Gnome terminal
3. maximize the terminal window (so that the title bar merges with the activity bar)
4. power the display off, then back on

## What happens
The terminal window again has its own title bar.

## What I expect to happen
For the terminal window title bar to remain merged with the activity bar.

## Further info
Under some circumstances (the specifics of which I haven't been able to narrow down), when the title bar comes back, it is entirely transparent, so that in place of a title bar you have a see-through hole. Here's [a screenshot, showing how part of Firefox's UI is visible from behind the terminal window](https://user-images.githubusercontent.com/4244772/40545533-d6ae6a82-6034-11e8-98c3-f683cdae470c.png), through where the title bar would be.

**Comment by tiotrom** [comment]
I can confirm that too. Same OS and Shell version.

**Comment by uusijani** [comment]
Alright, from my brief testing it would seem this does not reproduce under Wayland.

My recipe above appears to be quite sensitive to details: I have a test user with a clean desktop (with little more customization apart from the extension), and there the recipe works just as written. On the other hand, with my main user account it doesn't. To clarify: while the steps listed above fail to reproduce the issue with my main account, my main account _does_ manifest the issue too; just not with those exact steps.

My main account starts up the Signal desktop client, Nextcloud client and some other stuff upon login, but so far I haven't found which of those (if any) causes this difference.

I was, however, able to reproduce the "see-through hole" effect under both accounts: instead of maximizing Gnome terminal (in step 3), I tile it to cover the left half of my screen, then start up Chrome/Firefox, tile _it_ over the terminal window (i.e. to also cover the left half of the screen), before turning the display off and on again. Firefox then also manifests the hole, as does Gnome terminal when brought back to foreground from below. (Chrome does not manifest the hole, but then again Chrome has always appeared oblivious to the extension here.)

I should mention that I'm leaving the display off for about 4-5 seconds before turning it back on again. I'm not sure if that makes any difference, I'm just doing to to be sure that the "I'm off" signal has time to propagate back to the system.

**Comment by torchlard** [comment]
I also encounter same issue under xorg. Every time I resume laptop from suspension, all titlebar appears, and then when I click on the windows, the titlebar disappears and leave empty gap.

**Comment by tiotrom** [comment]
the only solution for now is to "F2", type "r", enter, so it restarts the Gnome Shell. Not convenient at all but well...i hope it will get sorted out

**Comment by CodingInTheUK** [comment]
I have just resolved this very issue, it might not be the case for you, check on the list type setting withing the settings for no-title-bar you will see three options, mine was set to whitelist with an empty list, what is odd however is that chrome seemed to be ignoring the whitelist option until i power cycled the monitor it was on. once i reverted back all seems fixed, power off/on has no adverse affect as far as i can see.

Ubuntu 18.04

**Comment by uusijani** [comment]
Tested this again and it seems to have been fixed at some point by some Ubuntu (18.04) updates: my test user still had version 8 of the extension, and I could no longer reproduce the issue, neither before nor after updating the extension to release v9. My main user's desktop now also appears unaffected.

(I was going to try the workaround reported by @ChrisLancs, but ended up not having to. My "List type" is set to "Disabled".)
