### ISSUE TITLE
Titlebar-less Firefox doesn't get blacklisted

### ISSUE THREAD

**Issue by adalvigi** [franglais125/no-title-bar#79]
I have an issue harmonizing Firefox with titlebar disabled (which thank goodness has been introduced on the latest version on Linux) and this extension. Both without any list, and by putting Firefox on the blacklist, I see buttons both on Firefox next to the tabs, and right above on the title-bar. I'd like the extension to not show the top bar buttons when Firefox is maximized as it already has them next to the tabs. The same issue arises with Firefox Developer edition (I blacklisted both and it works for none of 'em). 
The funniest part perhaps is that they get indeed blacklisted in some way, as, if I activate the titlebar, they don't lose it when maximized, but the minimize, window, close buttons still appear on the top bar as well as on the title bar.

Perhaps the bug is that blacklist, while not removing the titlebar from the blacklisted apps, doesn't prevent making the buttons on the top bar appear for them?

**Comment by franglais125** [comment]
This was addressed by PR https://github.com/franglais125/no-title-bar/pull/86. Thanks for reporting the issue!
