### ISSUE TITLE
Windows buttons show in top bar when not maximized

### ISSUE THREAD

**Issue by dboy591** [franglais125/no-title-bar#88]
Ubuntu 18.04.1 with Gnome 3.28 and installed from git.  

Window buttons are shown in the top bar even when the window is not maximized.   

Tested with and without blacklist enabled.  Also tested with "Show buttons for all windows" disabled.

**Comment by dboy591** [comment]
Something in commit **9bef2ca** is causing the issue.

**Comment by franglais125** [comment]
Thanks for reporting+fixing! Fixed at [54ea99c3abfaa37ba409212ff884bb1e58669e8f].
