### ISSUE TITLE
A lot of xprop become zombies and will slow down the machine until all memory is used up.

### ISSUE THREAD

**Issue by BoleynSu** [franglais125/no-title-bar#9]

**Comment by franglais125** [comment]
Hi! Thanks a lot for opening this issue.

It was already reported here https://github.com/franglais125/no-title-bar/issues/7, and I've already updated the extension to fix it. It's still under review (https://extensions.gnome.org/review/7192).

However, you can try the code directly from git master. It would be great if you could confirm that the latest version (4) fixes the issue for you too.

Cheers!

**Comment by BoleynSu** [comment]
cool I will try it thx

**Comment by franglais125** [comment]
Perfect, thank you!
