### ISSUE TITLE
[Duplicate] Possible to disable for snapped windows?

### ISSUE THREAD

**Issue by emichael** [franglais125/no-title-bar#94]
Hopefully simple feature request: It would be nice to have the option to disable no-title-bar for snapped windows. That is, I want to remove the title bar for maximized windows, but not for windows snapped to the left or right.

**Comment by Coeur-Noir** [comment]
https://github.com/franglais125/no-title-bar/issues/50

**Comment by emichael** [comment]
I see. Sorry for the dupe.
